-- ============================================================================
-- Migration 002: Auth, ownership, per-URL metadata, versioning, claim tokens.
--
-- Apply with: psql "$DATABASE_URL" -f db/migrations/002_auth_ownership.sql
--
-- Idempotent: safe to re-run. Every statement uses `IF NOT EXISTS` / `IF EXISTS`.
-- Do NOT edit this file after it has been applied to production. Write a new
-- migration instead.
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Identity mirror.
-- Clerk is the source of truth for users / organizations; these tables are a
-- local denormalization so every query can JOIN on a stable foreign key
-- without a Clerk round-trip. Rows are written by the Clerk webhook handler.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
  clerk_user_id      TEXT PRIMARY KEY,
  email              TEXT,
  display_name       TEXT,
  avatar_url         TEXT,
  -- Populated by Stripe customer creation on the first Clerk `user.created` event.
  stripe_customer_id TEXT UNIQUE,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS organizations (
  clerk_org_id       TEXT PRIMARY KEY,
  name               TEXT NOT NULL,
  slug               TEXT UNIQUE,
  stripe_customer_id TEXT UNIQUE,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS memberships (
  clerk_user_id TEXT NOT NULL REFERENCES users(clerk_user_id) ON DELETE CASCADE,
  clerk_org_id  TEXT NOT NULL REFERENCES organizations(clerk_org_id) ON DELETE CASCADE,
  -- Stores Clerk's role slug verbatim (e.g. "admin", "basic_member", or a
  -- custom role configured in the Clerk dashboard). Application code maps
  -- these to Linky-specific permissions.
  role          TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (clerk_user_id, clerk_org_id)
);

CREATE INDEX IF NOT EXISTS idx_memberships_clerk_org_id
  ON memberships (clerk_org_id);

-- ---------------------------------------------------------------------------
-- Entitlements.
-- Plan + per-subject limits. Read by the API layer on every gated call.
-- In Sprint 1, all subjects default to the `free` plan with a fixed limits
-- blob defined in application code (no rows required). Stripe webhooks will
-- populate rows here when paid plans go live.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS entitlements (
  subject_type           TEXT NOT NULL CHECK (subject_type IN ('user', 'org')),
  subject_id             TEXT NOT NULL,
  plan                   TEXT NOT NULL DEFAULT 'free',
  -- Flexible blob, e.g. { "max_linkies": 50, "max_urls_per_linky": 25, "analytics_days": 7 }.
  limits                 JSONB NOT NULL DEFAULT '{}'::jsonb,
  stripe_subscription_id TEXT,
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (subject_type, subject_id)
);

-- ---------------------------------------------------------------------------
-- Extend linkies with ownership and editing metadata.
-- Anonymous linkies keep both owner columns NULL. Ownership is enforced in
-- the application layer (PATCH/DELETE reject anonymous rows).
-- ---------------------------------------------------------------------------

ALTER TABLE linkies
  ADD COLUMN IF NOT EXISTS owner_user_id TEXT
    REFERENCES users(clerk_user_id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS owner_org_id  TEXT
    REFERENCES organizations(clerk_org_id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS title         TEXT,
  ADD COLUMN IF NOT EXISTS description   TEXT,
  -- Positional array aligned with `urls`. Entry shape:
  --   { note?: string, tags?: string[], openPolicy?: "desktop"|"mobile"|"always" }
  ADD COLUMN IF NOT EXISTS url_metadata  JSONB NOT NULL DEFAULT '[]'::jsonb,
  -- Hashed IP + User-Agent fingerprint captured at create time. Lets a user
  -- later claim an anonymous linky they (probably) created without requiring
  -- an email at create time. Claim via the claim_tokens flow below.
  ADD COLUMN IF NOT EXISTS creator_fingerprint TEXT,
  ADD COLUMN IF NOT EXISTS updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS deleted_at    TIMESTAMPTZ,
  -- Reserved for Sprint 2 (URL-as-API resolution policy). Empty for now.
  -- Shape will evolve; treat as opaque JSONB until then.
  ADD COLUMN IF NOT EXISTS resolution_policy JSONB NOT NULL DEFAULT '{}'::jsonb;

-- Enforce positional alignment: url_metadata must be an array.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'linkies_url_metadata_is_array'
  ) THEN
    ALTER TABLE linkies
      ADD CONSTRAINT linkies_url_metadata_is_array
      CHECK (jsonb_typeof(url_metadata) = 'array');
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_linkies_owner_user
  ON linkies (owner_user_id) WHERE owner_user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_linkies_owner_org
  ON linkies (owner_org_id) WHERE owner_org_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_linkies_deleted_at
  ON linkies (deleted_at);

-- ---------------------------------------------------------------------------
-- Append-only version history for edits.
-- Every PATCH inserts one row. Public resolution always reads `linkies`
-- (current state); history powers undo, audit, and future diffing.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS linky_versions (
  id                      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  linky_id                INTEGER NOT NULL REFERENCES linkies(id) ON DELETE CASCADE,
  version_number          INTEGER NOT NULL,
  urls                    JSONB   NOT NULL,
  url_metadata            JSONB   NOT NULL,
  title                   TEXT,
  description             TEXT,
  edited_by_clerk_user_id TEXT,
  edited_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (linky_id, version_number)
);

CREATE INDEX IF NOT EXISTS idx_linky_versions_linky_id
  ON linky_versions (linky_id, version_number DESC);

-- ---------------------------------------------------------------------------
-- Claim tokens.
-- Powers the "agent creates a Linky on your behalf" flow: backend mints a
-- token + optional email, returns a claim URL, user signs in and the linky's
-- ownership is transferred to their Clerk user.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS claim_tokens (
  token        TEXT PRIMARY KEY,
  linky_id     INTEGER NOT NULL REFERENCES linkies(id) ON DELETE CASCADE,
  -- Optional: when present, we'll pre-fill the Clerk sign-up form and can
  -- optionally email the claim URL.
  email        TEXT,
  expires_at   TIMESTAMPTZ NOT NULL,
  consumed_at  TIMESTAMPTZ,
  consumed_by_clerk_user_id TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_claim_tokens_linky_id
  ON claim_tokens (linky_id);

CREATE INDEX IF NOT EXISTS idx_claim_tokens_expires_at
  ON claim_tokens (expires_at);

COMMIT;
