-- ============================================================================
-- Migration 005: launcher_events — owner-side analytics.
--
-- Apply with: psql "$DATABASE_URL" -f db/migrations/005_launcher_events.sql
--
-- Idempotent: safe to re-run.
-- Do NOT edit this file after it has been applied to production. Write a new
-- migration instead.
--
-- Context: Sprint 2.7 Chunk A. Every render of /l/[slug] writes one 'view'
-- row; every Open All click writes one 'open_all' row. Aggregated into the
-- owner-facing insights panel (Chunk B).
--
-- Trust posture (README.md "Trust & lifecycle policy" bullet 9):
--   - We store NO raw IP, NO user-agent, NO email, NO Clerk id.
--   - `viewer_hash_day` is sha256(subject || YYYY-MM-DD || daily_salt). The
--     daily salt rotation means "unique viewers per day" is answerable in
--     aggregate; cross-day identity is intentionally not recoverable.
--   - `matched_rule_id` is whatever id the policy parser minted at author
--     time. If the owner deletes the rule later the id dangles — Chunk B
--     renders dangling ids as "(removed rule)". No FK; the policy lives in
--     a JSONB column by design.
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS launcher_events (
  id                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  linky_id          INTEGER NOT NULL REFERENCES linkies(id) ON DELETE CASCADE,
  kind              TEXT NOT NULL,
  occurred_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  matched_rule_id   TEXT,
  viewer_state      TEXT NOT NULL,
  viewer_hash_day   TEXT NOT NULL
);

-- `kind` and `viewer_state` are closed enums. We enforce them with CHECK
-- constraints rather than a separate lookup table so the DSL stays in-file
-- and a bad write fails loudly.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'launcher_events_kind_check'
  ) THEN
    ALTER TABLE launcher_events
      ADD CONSTRAINT launcher_events_kind_check
      CHECK (kind IN ('view', 'open_all'));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'launcher_events_viewer_state_check'
  ) THEN
    ALTER TABLE launcher_events
      ADD CONSTRAINT launcher_events_viewer_state_check
      CHECK (viewer_state IN ('anonymous', 'signed_in'));
  END IF;
END
$$;

-- Aggregation queries ("views for linky X in the last N days") always filter
-- by linky_id and time, so this is the only index we need.
CREATE INDEX IF NOT EXISTS idx_launcher_events_linky_time
  ON launcher_events (linky_id, occurred_at DESC);

COMMIT;
