-- ============================================================================
-- Migration 006: API-key scopes.
--
-- Apply with: psql "$DATABASE_URL" -f db/migrations/006_api_key_scopes.sql
--
-- Idempotent: safe to re-run.
-- Do NOT edit this file after it has been applied to production. Write a new
-- migration instead.
--
-- Context: Sprint 2.7 Chunk D. Before this migration every API key carried
-- implicit full-edit authority (Sprint 2.6 shipped one scope level: 'edit
-- as this subject'). That's the wrong shape for any LLM-held credential —
-- one leaked key = full delete authority.
--
-- After this migration, keys carry an explicit `scopes` array. Existing
-- keys default to ['links:write'] to preserve today's behavior. New keys
-- pick from the allow-list:
--
--   links:read   — list + view Linkies, read insights. Safe for LLM
--                  context. Explicitly cannot PATCH or DELETE.
--   links:write  — everything links:read can do, plus PATCH.
--                  DELETE still requires admin role (Chunk C gate).
--   keys:admin   — everything links:write can do, plus manage API keys.
--                  Intentionally rare; off by default.
--
-- Implication is resolved at runtime by expandScopes() in api-keys.ts —
-- the stored array is exactly what the caller asked for, no smuggling.
-- ============================================================================

BEGIN;

-- Default preserves today's behavior: every existing row is 'links:write'.
-- Fresh inserts MUST pass the scopes array explicitly (the app code does;
-- the default is a safety-net for hand-written INSERTs).
ALTER TABLE api_keys
  ADD COLUMN IF NOT EXISTS scopes JSONB NOT NULL DEFAULT '["links:write"]'::jsonb;

-- Enforce that the column is always a JSON array so application code can
-- rely on it. The shape of the entries is further validated by
-- expandScopes() in api-keys.ts at read + write time.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'api_keys_scopes_is_array'
  ) THEN
    ALTER TABLE api_keys
      ADD CONSTRAINT api_keys_scopes_is_array
      CHECK (jsonb_typeof(scopes) = 'array');
  END IF;
END
$$;

COMMIT;
